default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost


development:
  <<: *default
  database: diary_development 
  
test:
  <<: *default
  database: diary_test
  
production:
  <<: *default
  database: diary_production
  username: diary
  password: <%= ENV['DIARY_DATABASE_PASSWORD'] %>